### ISSUE TITLE
Your experience with RayLib?

### ISSUE THREAD

**Issue by ghost** [ProfJski/ArtColors#2]
Hello, 
I loved the app you wrote.  I am in the midst of choosing a UI lib for a combined C++/ WebAssembly based project. In general, is your experience positive ith RayLib? Have you ever made any attempt to port it to WASM? 

Many thanks,

**Comment by ProfJski** [comment]
@QuantScientist: Thanks for your kind comment!  Coding has taken a back seat to teaching through COVID so I haven't posted anything for a while.  I'd like to return to ArtColors code eventually, mainly to test the colors on calibrated equipment and export the main color mixing function as a stand-alone function via an include.

I have found RayLib very easy to implement.  It is performant.  I've used it with OpenCL on AMD + hundreds of thousands of objects rendered through it for a many-body physics sim.  It's lean.  No external dependencies is nice.  The lead dev (RaySan5) is very attentive and helpful, as is the Discord community.  They have answered lots of my questions, from small or newbie questions to more complex ones.  I have checked out Wasm but I haven't actually compiled code to it yet.  You could ask RaySan or the Discord site about that.  They also have a lot of bindings (Rust, LUA, etc.) in progress.  While I have only used it on Windows and Linux, it should be able to run a wide variety of platforms if you are developing something cross-platform.

For my math / physics code, I just wanted something that let me put plenty of primitives on the screen with minimal overhead and a short learning curve.  RayLib has been perfect for that!

The GUI is an additional module.  It is extremely easy to add on.  It gets the job done for the basic IO that I need it to do.  It's good for getting small, tidy text on the screen with the default font, and I know it has additional features that I haven't bothered to use (custom fonts, default styles) that can make it look more professional.  The nice thing about an immediate-mode UI is that you don't have to mess with hooks and events.  I mainly use it for dialing in parameters to my largely mathematical code.  As with any GUI, there's always fussing around with layout.  RayGUI's default way is by pixel location, but it would be easy to modify to percentage of screen width and height for multiple screen sizes.  If you are accustomed to a drag-and-drop GUI layout editor, you may find layout a step backwards in terms of convenience, but the most I've had to do is draw a sketch or two on graph paper for anything that I couldn't eyeball.

**Comment by ProfJski** [comment]
Forgot to close this one a while ago. :-)
